### PR TITLE
Fix: Show order date in minimalist view

### LINKED ISSUE #483: Modificación en lógica minimalista de columnas en Ventanas
## Bug report
Con la lógica que se aplicó actualmente existen algunos campos que considero que deberían mostrarse siempre, pero quedan fuera de la lógica que aplicaron para lo "Minimalista" de ser Obligatorio y no tener una lógica predeterminada. Por ejemplo en las órdenes de venta el campo "FECHA DE LA ORDEN" o "FECHA PROMETIDA" si bien tiene una lógica predeternimada y son obligatorios, si se desea modificar la fecha se debe primero agregar el capo y luego modifciarla lo cual no tiene mucho sentido. Lo mismo sucede con el campo "Cantidad" de las líneas de Orden.

En este sentido, y siguiendo el criterio definido para mostrar los campos por defecto en las formas de búsqueda de Socio del Negocio y Productos, se sugiere agregar a la lógica "Minimalista" también las olumnas que estén marcadas como "Columna Selección" (Selection Column)

De esta manera también se permite un ágil mantenimiento si se desea aplicar una modificación de los campos a mostrar en un cliente específico.

image

### PR DESCRIPTION
**Pull request by elsiosanchez**
### _**GIF**_

https://user-images.githubusercontent.com/45974454/204653565-8a10d36f-ce76-4e3e-9c2c-7cadd0b13215.mp4

### _**ISSUES**_

Fixed:  [#483](https://github.com/solop-develop/frontend-core/issues/483)

### CODE REVIEW

File: components/ADempiere/DataTable/Windows/index.vue [hunk 1]
```diff
@@ -409,6 +409,19 @@ export default defineComponent({
       }
     }
 
+    /**
+     * isDisplayedDefaultTable
+     */
+    function isDisplayedDefaultTable({ isMandatory, isParent, defaultValue, displayType, parsedDefaultValue, name }) {
+      if (displayType === 15) {
```
Comment (EdwinBetanc0urt) [inline components/ADempiere/DataTable/Windows/index.vue]: Please import constant on src/utils/ADempiere/references.js and compare with CONSTANT.id

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]
