### PR TITLE
Fix: Show and Hide Fields in Customization

### LINKED ISSUE #710: Drag and Drop: Ventana > Guardar secuencia campos de pestañas.
https://user-images.githubusercontent.com/45974454/212110802-deafd8a5-2b03-44b6-b150-20fa03985635.mp4

### LINKED ISSUE #712: Drag and Drop: Proceso > Guardar secuencia parámetros de procesos.

### LINKED ISSUE #715: Drag and Drop: Reporte > Guardar secuencia parámetros de reportes.

### LINKED ISSUE #716: Drag and Drop: Consulta Inteligente > Guardar secuencia campos de consultas inteligentes.

### PR DESCRIPTION
**Pull request by elsiosanchez**
### _**GIF**_

https://user-images.githubusercontent.com/45974454/215798568-b714ce77-bb83-4d97-9644-3be919a7a2fe.mp4

#### Additional context
fixes https://github.com/solop-develop/frontend-core/issues/716
fixes https://github.com/solop-develop/frontend-core/issues/712
fixes https://github.com/solop-develop/frontend-core/issues/710
fixes https://github.com/solop-develop/frontend-core/issues/715

### CODE REVIEW

File: components/ADempiere/PanelDefinition/DraggablePanel.vue [hunk 1]
```diff
@@ -86,11 +91,12 @@ along with this program. If not, see <https:www.gnu.org/licenses/>.
 </template>
 
 <script>
-import { defineComponent, computed } from '@vue/composition-api'
+import { defineComponent, computed, ref, watch } from '@vue/composition-api'
 
 import store from '@/store'
 
 // Components and Mixins
+import LoadingView from '@theme/components/ADempiere/LoadingView/index.vue'
```
Comment (EdwinBetanc0urt) [inline components/ADempiere/PanelDefinition/DraggablePanel.vue]: please remove loading

File: components/ADempiere/PanelDefinition/DraggablePanel.vue [hunk 2]
```diff
@@ -136,6 +143,9 @@ export default defineComponent({
 
   setup(props) {
     // const draggableFieldsList = ref([])
+    const draggableList = ref([])
+    const isLoading = ref(false)
```
Comment (EdwinBetanc0urt) [inline components/ADempiere/PanelDefinition/DraggablePanel.vue]: please remove loading

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
