### PR TITLE
Fix: Add option next and previous

### LINKED ISSUE #625: 1.2 agregar la opción de "Siguiente Registro" cuando se está en modo mono registro. o la paginación también cuando se ve en mono registro.
image

### PR DESCRIPTION
**Pull request by elsiosanchez**
### _**GIF**_

https://user-images.githubusercontent.com/45974454/205724660-13a5749b-6588-4152-9e8c-9b80427fb183.mp4

### _**ISSUES**_

Fixed: [#625](https://github.com/solop-develop/frontend-core/issues/625)

### CODE REVIEW

File: components/ADempiere/TabManager/TabOptions.vue [hunk 1]
```diff
@@ -218,32 +220,52 @@ export default defineComponent({
     })
 
     function changeShowedRecords() {
-      const isSelectionRow = props.containerManager.getSelection({
+      // const isSelectionRow = props.containerManager.getSelection({
```
Comment (EdwinBetanc0urt) [inline components/ADempiere/TabManager/TabOptions.vue]: please remove this code

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]
Please upload a video capture with a smart browser in this branch, as it uses the paging component.

**Review by EdwinBetanc0urt — APPROVED** [review]
