### PR TITLE
Fix: Zooming in from Business Partner

### LINKED ISSUE #601: Acercar desde Campo Socio del Negocio no abre el registro desde donde se navegó
## Bug report
Al acercar en un registro, en ZK abría la ventana definida pero en el registro desde donde se está acercando.

Ahora si bien abre correctamente la ventana de la tabla del registro,  no muestra el Socio del Negocio desde donde se navegó.

Se intenta también guardando el registro pero tampoco lleva al ID del SDN definido en el campo.

#### Screenshot or Gif（截图或动态图）

https://user-images.githubusercontent.com/31936815/203600078-7e7b845f-98f0-4fa4-abc5-c531c26d489e.mp4

### PR DESCRIPTION
**Pull request by elsiosanchez**
### _**BUGFIX**_
Zooming in from Business Partner Field does not open the record from where it was navigated
### _**GIF**_

https://user-images.githubusercontent.com/45974454/204008007-59897277-67e5-4fee-86d8-5970dec187c4.mp4

### _**ISSUES**_

Fixed: [#601](https://github.com/solop-develop/frontend-core/issues/601)

### CODE REVIEW

File: components/ADempiere/FieldDefinition/FieldProductAttribute/panelProductAttribute.vue [hunk 1]
```diff
@@ -305,6 +305,12 @@ export default {
         field: this.metadata,
         columnName
       })
+      this.$store.dispatch('flushPersistenceQueue', {
+        parentUuid,
+        containerUuid,
```
Comment (EdwinBetanc0urt) [inline components/ADempiere/FieldDefinition/FieldProductAttribute/panelProductAttribute.vue]: This change does not apply to the pull request

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
